spring:
  profile.active: dev, test, prop
  datasource:
    url: jdbc:mysql://localhost/foro_hub_bd
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-stacktrace: never

api:
  security:
    secret: ${JWT_SECRET:123456}

